# wrangler.toml
name = "blog"
pages_build_output_dir = "./dist"
compatibility_date = "2026-06-11"

[[kv_namespaces]]
#preview_id = "preview_id"
binding = "blog-session"
id = "79d0182e6d2a403490c657e5f9bb87d3"

[assets]
directory = "./dist"